(()=>{
const DEFAULT_DRESSES = [
  {id:'aurora',code:'ORG-01',name:'Aurora',color:'dourado',colorName:'Dourado',swatch:'#d4b567',subtitle:'O brilho de um novo começo',description:'Um dourado luminoso, com bordados no corpete e saia ampla. Nas costas, as camadas de tule revelam um outro jeito de encantar.',images:[['640326387','Frente'],['639835043','Costas']]},
  {id:'ceu',code:'ORG-02',name:'Céu',color:'azul',colorName:'Azul',swatch:'#86b6e9',subtitle:'Um sonho em azul',description:'Azul delicado, decote ombro a ombro e uma saia cheia de movimento. As fotos de frente e costas mostram o brilho do tecido e o volume das camadas.',images:[['809910695','Frente'],['797784121','Costas']]},
  {id:'lavanda',code:'ORG-03',name:'Lavanda',color:'lilas',colorName:'Lilás',swatch:'#bca2dc',subtitle:'Delicadeza em cada camada',description:'Tons de lilás, aplicações florais e uma saia em camadas de tule. Um vestido romântico para viver um momento inesquecível.',images:[['710246063','Frente']]},
  {id:'aqua',code:'ORG-04',name:'Aqua',color:'verde',colorName:'Verde água',swatch:'#9cdbcb',subtitle:'Uma cor, várias possibilidades',description:'Verde água com brilho, mangas delicadas e corpete estruturado. Explore o visual longo, a versão curta e os detalhes do bordado nas fotos deste mesmo modelo.',images:[['694685607','Versão longa'],['692809341','Versão curta'],['688951249','Detalhe da saia'],['688964802','Detalhe do corpete']]},
  {id:'rose',code:'ORG-05',name:'Rosé',color:'rosa',colorName:'Rosa',swatch:'#e8b6c7',subtitle:'Romance para o seu grande dia',description:'Rosa suave com saia volumosa em camadas, bordados e corpete com decote coração. Uma silhueta de princesa para o seu grande dia.',images:[['716170320','Frente']]},
  {id:'rubi',code:'ORG-06',name:'Rubi',color:'vermelho',colorName:'Vermelho',swatch:'#9e233a',subtitle:'Para uma entrada inesquecível',description:'Vermelho intenso, bordados que refletem a luz e uma saia de camadas marcantes. Um vestido para quem se imagina brilhando em cada passo.',images:[['718069101','Frente']]},
  {id:'jardim',code:'ORG-07',name:'Jardim',color:'rosa',colorName:'Rosa floral',swatch:'#d9aac8',subtitle:'Flores que contam uma história',description:'Rosa delicado, aplicações florais e detalhes nos ombros. A saia ampla de tule traz leveza para uma celebração cheia de encanto.',images:[['720950405','Frente']]}
];
const key='organzza-catalog-v1';
const pricingVersion='organzza-demo-pricing-v1';
const pricePlans={aurora:{price:1000,promoPrice:850},ceu:{price:1100,promoPrice:930},lavanda:{price:950,promoPrice:800},aqua:{price:1400,promoPrice:1190},rose:{price:1200,promoPrice:1020},rubi:{price:1300,promoPrice:1100},jardim:{price:1150,promoPrice:980}};
const clone=v=>JSON.parse(JSON.stringify(v));
const colors={azul:['azul','#86b6e9'],rosa:['rosa','#e8b6c7'],lilas:['lilas','#bca2dc'],verde:['verde','#9cdbcb'],dourado:['dourado','#d4b567'],vermelho:['vermelho','#9e233a']};
const defaultProducts=DEFAULT_DRESSES.map(d=>({...d,cat:'Debutantes',color:d.colorName,filterKey:d.color,images:d.images.map(([f])=>'assets/'+f+'.webp'),photoLabels:Object.fromEntries(d.images.map(([f,l])=>['assets/'+f+'.webp',l])),...pricePlans[d.id],stock:1,active:true,sizes:[],material:'',occasion:'15 anos',care:''}));
function colorKey(value){const s=String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(s.includes('azul'))return 'azul';if(s.includes('rosa')||s.includes('rose'))return 'rosa';if(s.includes('lilas')||s.includes('lavanda'))return 'lilas';if(s.includes('verde')||s.includes('aqua'))return 'verde';if(s.includes('doura')||s.includes('ouro'))return 'dourado';if(s.includes('vermelh')||s.includes('rubi'))return 'vermelho';return 'outros';}
function normalize(product){const base=defaultProducts.find(d=>d.id===product.id)||{};const color=String(product.color||base.color||'A confirmar');const filterKey=colorKey(color);const numeric=value=>value!==null&&value!==''&&Number(value)>0?Number(value):null;return {...base,...product,id:String(product.id),name:String(product.name||'Vestido'),code:String(product.code||base.code||'ORG-'+String(product.id).slice(-5).toUpperCase()),color,colorName:color,filterKey,swatch:colors[filterKey]?.[1]||'#b9b3a7',subtitle:String(product.subtitle||base.subtitle||'Para o seu grande momento'),price:numeric(product.price),promoPrice:numeric(product.promoPrice),stock:Math.max(0,Math.floor(Number(product.stock)||0)),active:product.active!==false,sizes:Array.isArray(product.sizes)?product.sizes.map(String):[],images:Array.isArray(product.images)?product.images.filter(src=>typeof src==='string'&&(/^(assets\/|data:image\/(jpeg|png|webp);base64,|https?:\/\/)/i.test(src))):[],photoLabels:product.photoLabels||base.photoLabels||{}};}
function getProducts(){let saved;try{saved=JSON.parse(localStorage.getItem(key)||'null');}catch{}let products=(Array.isArray(saved)?saved:clone(defaultProducts)).map(normalize);try{if(localStorage.getItem(pricingVersion)!=='1'){products=products.map(product=>pricePlans[product.id]?{...product,...pricePlans[product.id]}:product);localStorage.setItem(key,JSON.stringify(products));localStorage.setItem(pricingVersion,'1');}}catch{}return products;}
function saveProducts(products){localStorage.setItem(key,JSON.stringify(products.map(normalize)));window.dispatchEvent(new CustomEvent('organzza-catalog-changed'));}
function resetDefaults(){const products=clone(defaultProducts);saveProducts(products);return products;}
window.CatalogStore={key,defaults:clone(defaultProducts),getProducts,saveProducts,resetDefaults};
})();
