(()=>{
  const escape=value=>String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const panel=document.createElement('section');panel.className='requests-panel';panel.id='solicitacoes';
  panel.innerHTML='<div class="requests-heading"><div><span class="eyebrow">PEDIDOS DE AGENDAMENTO</span><h2>Solicitações de prova <span id="pendingRequests">0</span></h2><p>Confira os pedidos de todas as datas. Aceite, recuse ou converse com a cliente para combinar outro horário.</p></div><button class="request-refresh" id="refreshRequests">Atualizar pedidos</button></div><div class="requests-toolbar"><div class="request-filters" role="group" aria-label="Filtrar agendamentos"><button data-request-filter="pending" class="active" aria-pressed="true">Pendentes</button><button data-request-filter="scheduled" aria-pressed="false">Aceitos</button><button data-request-filter="rejected" aria-pressed="false">Recusados</button><button data-request-filter="all" aria-pressed="false">Todos</button></div><input id="requestSearch" type="search" placeholder="Buscar cliente ou telefone..." aria-label="Buscar agendamentos"></div><p id="requestConnection" role="status"></p><div id="requestList" class="request-list" aria-live="polite"></div>';
  document.querySelector('#acervo').before(panel);
  const nav=document.createElement('a');nav.href='#solicitacoes';nav.innerHTML='◷ <span>Agendamentos <b id="requestNavCount">0</b></span>';document.querySelector('.sidebar nav a[href="#acervo"]').before(nav);
  nav.addEventListener('click',()=>{document.querySelectorAll('.sidebar nav a').forEach(a=>a.classList.toggle('active',a===nav));document.querySelector('.sidebar').classList.remove('open');document.querySelector('#sideOverlay').classList.remove('show');});
  const dialogs=document.createElement('div');dialogs.innerHTML='<dialog class="refusal-dialog" id="refusalDialog"><form id="refusalForm"><header><div><span class="eyebrow">PEDIDO DE PROVA</span><h2>Recusar este horário</h2></div><button type="button" id="refusalClose" aria-label="Fechar">×</button></header><div class="refusal-body"><p id="refusalSummary"></p><label>Motivo ou sugestão de outra data <span>(opcional)</span><textarea id="refusalReason" rows="4" maxlength="500" placeholder="Ex.: Não conseguimos atender neste horário. Podemos combinar uma nova data pelo WhatsApp."></textarea></label><p>O horário será liberado. Depois, use o botão de WhatsApp para conversar com a cliente.</p></div><footer><button type="button" class="secondary" id="refusalCancel">Voltar</button><button type="submit" class="primary">Recusar pedido</button></footer></form></dialog><dialog class="admin-login" id="adminLogin"><form id="adminLoginForm"><header><div><span class="eyebrow">ORGANZZA DEBUTANTES</span><h2>Entrar no painel</h2></div></header><div class="refusal-body"><label>Senha da administração<input name="password" type="password" required autocomplete="current-password"></label><p id="loginError" role="alert"></p><button class="primary" type="submit">Entrar</button></div></form></dialog>';
  document.body.append(dialogs);
  const statusNames={pending:'Aguardando aceite',scheduled:'Aceito',rejected:'Recusado',cancelled:'Cancelado',completed:'Concluído'};
  let filter='pending',refusingId=null,busy=false;
  const date=value=>{const d=AppointmentStore.parseLocalDate(value);return d?d.toLocaleDateString('pt-BR'): 'A combinar';};
  function whatsapp(item){let phone=item.phone.replace(/\D/g,'');if(phone.length===10||phone.length===11)phone='55'+phone;if(!/^\d{10,15}$/.test(phone))return null;let message=`Olá, ${item.clientName}! Aqui é da Organzza Debutantes. `;if(item.status==='scheduled')message+=`Sua prova está confirmada para ${date(item.date)}, às ${item.time}. Podemos conversar sobre os vestidos que você escolheu?`;else if(item.status==='rejected')message+=`Não conseguimos confirmar a prova solicitada para ${date(item.date)}, às ${item.time}. ${item.refusalReason?item.refusalReason+' ':''}Podemos combinar outra data ou horário?`;else message+=`Recebemos seu pedido de prova para ${date(item.date)}, às ${item.time}. Vamos conversar para confirmar o atendimento ou combinar outra data?`;return 'https://api.whatsapp.com/send/?phone='+phone+'&text='+encodeURIComponent(message);}
  function render(){
    const appointments=AppointmentStore.getAppointments(),pending=appointments.filter(a=>a.status==='pending').length;
    document.querySelector('#pendingRequests').textContent=pending;document.querySelector('#requestNavCount').textContent=pending;
    const query=document.querySelector('#requestSearch').value.trim().toLocaleLowerCase('pt-BR');
    const items=appointments.filter(a=>(filter==='all'||a.status===filter)&&[a.clientName,a.phone].join(' ').toLocaleLowerCase('pt-BR').includes(query)).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time)||b.createdAt.localeCompare(a.createdAt));
    document.querySelectorAll('[data-request-filter]').forEach(b=>{const selected=b.dataset.requestFilter===filter;b.classList.toggle('active',selected);b.setAttribute('aria-pressed',selected);});
    document.querySelector('#requestList').innerHTML=items.map(a=>{const link=whatsapp(a);const dresses=a.dresses.map(d=>typeof d==='string'?d:(d.name||d.id||'Vestido')+(d.size?' · tamanho '+d.size:'')).join(', ');return `<article class="request-card ${escape(a.status)}" data-request-id="${escape(a.id)}"><div class="request-card-top"><span class="request-status">${statusNames[a.status]}</span><span>${a.source==='site'?'Pedido pelo site':'Atendimento da loja'}</span></div><h3>${escape(a.clientName)}</h3><a class="request-phone" href="tel:${escape(a.phone.replace(/\D/g,''))}">${escape(a.phone||'Telefone não informado')}</a><dl><div><dt>Prova solicitada</dt><dd>${date(a.date)} às ${escape(a.time)}</dd></div><div><dt>Data da festa</dt><dd>${a.eventDate?date(a.eventDate):'A confirmar'}</dd></div><div class="wide"><dt>Vestidos de interesse</dt><dd>${escape(dresses||'A definir')}</dd></div>${a.notes?`<div class="wide"><dt>Observações</dt><dd>${escape(a.notes)}</dd></div>`:''}${a.refusalReason?`<div class="wide"><dt>Motivo da recusa</dt><dd>${escape(a.refusalReason)}</dd></div>`:''}${a.requestedDate!==a.date||a.requestedTime!==a.time?`<div class="wide"><dt>Pedido original</dt><dd>${date(a.requestedDate)} às ${escape(a.requestedTime)}</dd></div>`:''}</dl><div class="request-actions">${a.status==='pending'?'<button class="primary" data-request-action="accept">Aceitar pedido</button><button class="request-outline" data-request-action="reject">Recusar</button>':''}${['pending','scheduled','rejected','cancelled'].includes(a.status)?'<button class="request-outline" data-request-action="reschedule">Remarcar</button>':''}${link?`<a class="request-whatsapp" href="${escape(link)}" target="_blank" rel="noopener noreferrer">Conversar no WhatsApp ↗</a>`:'<span class="invalid-phone">Informe um telefone válido para abrir o WhatsApp.</span>'}<button class="request-calendar" data-request-action="calendar">Ver na agenda ↓</button></div></article>`;}).join('')||'<div class="requests-empty"><strong>Nenhum pedido neste filtro.</strong><p>Os pedidos de prova feitos pelo site aparecerão aqui.</p></div>';
  }
  function feedback(message){const el=document.querySelector('#requestConnection');el.textContent=message;}
  async function update(id,patch){if(busy)return false;busy=true;try{const items=AppointmentStore.getAppointments(),index=items.findIndex(i=>i.id===id);if(index<0)throw Error('Pedido não encontrado. Atualize a lista.');items[index]={...items[index],...patch};await AppointmentStore.saveAppointments(items);feedback(patch.status==='scheduled'?'Agendamento aceito. Use o WhatsApp para confirmar com a cliente.':'Pedido recusado e horário liberado. Você pode combinar outra data pelo WhatsApp.');return true;}catch(error){feedback(error.message);await AppointmentStore.refresh().catch(()=>{});return false;}finally{busy=false;render();}}
  panel.addEventListener('click',async e=>{const f=e.target.closest('[data-request-filter]');if(f){filter=f.dataset.requestFilter;render();return;}const button=e.target.closest('[data-request-action]');if(!button)return;const id=button.closest('[data-request-id]').dataset.requestId,item=AppointmentStore.getAppointments().find(i=>i.id===id);if(!item)return;
    if(button.dataset.requestAction==='accept'){button.disabled=true;await update(id,{status:'scheduled'});}
    if(button.dataset.requestAction==='reject'){refusingId=id;document.querySelector('#refusalSummary').textContent=`${item.clientName} · ${date(item.date)} às ${item.time}`;document.querySelector('#refusalReason').value='';document.querySelector('#refusalDialog').showModal();}
    if(button.dataset.requestAction==='reschedule')window.AdminAppointments.open({...item,status:'scheduled',refusalReason:''});
    if(button.dataset.requestAction==='calendar'){const input=document.querySelector('#agendaDate');input.value=item.date;input.dispatchEvent(new Event('change'));document.querySelector('#agenda').scrollIntoView({behavior:'smooth'});}
  });
  document.querySelector('#requestSearch').addEventListener('input',render);
  document.querySelector('#refreshRequests').addEventListener('click',async e=>{e.target.disabled=true;try{await AppointmentStore.refresh();feedback('Pedidos atualizados.');}catch(error){feedback(error.message);}finally{e.target.disabled=false;}});
  for(const id of ['refusalClose','refusalCancel'])document.querySelector('#'+id).addEventListener('click',()=>document.querySelector('#refusalDialog').close());
  document.querySelector('#refusalForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.currentTarget.querySelector('[type="submit"]');button.disabled=true;const ok=await update(refusingId,{status:'rejected',refusalReason:document.querySelector('#refusalReason').value.trim()});button.disabled=false;if(ok)document.querySelector('#refusalDialog').close();});
  window.addEventListener('organzza-appointments-updated',render);
  window.addEventListener('organzza-bookings-error',e=>{if(e.detail.status===401&&!document.querySelector('#adminLogin').open)document.querySelector('#adminLogin').showModal();else feedback(e.detail.message);});
  document.querySelector('#adminLogin').addEventListener('cancel',e=>e.preventDefault());
  document.querySelector('#adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.currentTarget.querySelector('[type="submit"]');button.disabled=true;try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:new FormData(e.currentTarget).get('password')})});const data=await r.json();if(!r.ok)throw Error(data.error);document.querySelector('#adminLogin').close();await AppointmentStore.refresh();feedback('Agendamentos atualizados.');}catch(error){document.querySelector('#loginError').textContent=error.message;}finally{button.disabled=false;}});
  AppointmentStore.ready.then(render);render();
})();
