import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,mkdtemp,rm} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import os from 'node:os';
import path from 'node:path';
const testDirectory=await mkdtemp(path.join(os.tmpdir(),'organzza-site-test-'));
const server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'4187',ORGANZZA_DATA_DIR:testDirectory,ADMIN_PASSWORD:''},stdio:'pipe',windowsHide:true});
for(let i=0;i<100;i++){try{if((await fetch('http://localhost:4187/api/availability')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('response',response=>{if(response.status()>=400&&response.url().startsWith('http://localhost:4187'))errors.push(`${response.status()} ${response.url()}`);});
try {
  await page.goto('http://localhost:4187');
  await page.evaluate(()=>document.fonts.ready);
  await page.evaluate(()=>{const products=CatalogStore.getProducts().map(d=>({...d,price:d.id==='aurora'?1000:null,promoPrice:d.id==='aurora'?850:null}));products.find(d=>d.id==='jardim').description='Texto editado preservado';localStorage.setItem(CatalogStore.key,JSON.stringify(products));localStorage.removeItem('organzza-demo-pricing-v1');});await page.reload();
  assert.equal(await page.locator('.product-promo').count(),7);assert.equal(await page.locator('.product-price del').count(),7);
  const pricing=await page.evaluate(()=>CatalogStore.getProducts());assert.equal(pricing.every(d=>d.price>d.promoPrice&&d.promoPrice>0),true);assert.equal(pricing.find(d=>d.id==='jardim').description,'Texto editado preservado');
  assert.equal(await page.locator('#header-whatsapp').count(),1);assert.equal(await page.locator('#saved-nav').count(),0);assert.equal(await page.locator('.hero-logo').count(),1);assert.equal(await page.locator('.hero-copy .button span').textContent(),'↓');
  assert.equal(await page.locator('.hero-copy .button').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(97, 35, 51)');
  assert.equal(await page.locator('.product-card').count(),7);
  assert.equal(await page.locator('#loja iframe').count(),1);assert.match(await page.locator('#loja address').textContent(),/817/);assert.match(await page.locator('#loja .store-hours').textContent(),/09h às 18h/);assert.match(await page.locator('#loja .store-hours').textContent(),/08h às 16h/);
  await page.locator('[data-color="rosa"]').click();assert.equal(await page.locator('.product-card').count(),2);
  await page.locator('[data-color="azul"]').click();assert.equal(await page.locator('.product-card').count(),1);
  await page.locator('[data-favorite="ceu"]').click();assert.match(await page.locator('#favorites-filter').textContent(),/\(1\)/);
  await page.reload();assert.match(await page.locator('#favorites-filter').textContent(),/\(1\)/);
  await page.locator('#favorites-filter').click();assert.equal(await page.locator('.product-card').count(),1);
  await page.locator('.open-product[data-dress="ceu"]').click();assert.equal(await page.locator('#dialog-title').textContent(),'Céu');
  assert.equal(await page.locator('#thumbnails button').count(),2);
  await page.locator('.next').click();assert.match(await page.locator('#gallery-image').getAttribute('src'),/797784121/);
  await page.keyboard.press('ArrowLeft');assert.match(await page.locator('#gallery-image').getAttribute('src'),/809910695/);
  const whatsapp=new URL(await page.locator('#dress-contact').getAttribute('href'));assert.equal(whatsapp.searchParams.get('phone'),'5527999073556');assert.match(whatsapp.searchParams.get('text'),/Céu \(ORG-02\)/);
  await page.keyboard.press('Escape');assert.equal(await page.locator('#product-dialog').evaluate(el=>el.open),false);
  await page.locator('#favorites-filter').click();await page.locator('[data-color="verde"]').click();
  await page.locator('.open-product[data-dress="aqua"]').click();assert.equal(await page.locator('#thumbnails button').count(),4);
  await page.locator('[data-photo="1"]').click();assert.match(await page.locator('#gallery-caption').textContent(),/Versão curta/);
  await page.locator('.dialog-close').click();
  await page.goto('http://localhost:4187/?vestido=aurora');assert.equal(await page.locator('#dialog-title').textContent(),'Aurora');assert.equal(await page.locator('#thumbnails button').count(),2);await page.locator('.dialog-close').click();
  await page.evaluate(()=>localStorage.removeItem('organzza-favorites'));await page.goto('http://localhost:4187');await page.evaluate(()=>document.fonts.ready);
  await page.locator('.product-card').last().scrollIntoViewIfNeeded();await page.waitForTimeout(400);await page.evaluate(()=>scrollTo(0,0));
  await mkdir('previews',{recursive:true});await page.screenshot({path:'previews/desktop.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  for(const width of [390,320,768]){
    await page.setViewportSize({width,height:844});await page.goto('http://localhost:4187');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`Overflow at ${width}px`);
    await page.locator('.open-product[data-dress="aurora"]').click();await page.locator('.next').click();assert.match(await page.locator('#gallery-caption').textContent(),/Costas/);
    assert.equal(await page.locator('#product-dialog').evaluate(el=>el.scrollWidth>el.clientWidth),false,`Dialog overflow at ${width}px`);
    await page.locator('.dialog-close').click();
    if(width===390){await page.locator('.product-card').last().scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'previews/mobile.png',fullPage:true});}
  }
  await page.setViewportSize({width:1440,height:1000});await page.goto('http://localhost:4187');
  assert.equal(await page.locator('.photo-caption a').count(),0);
  assert.equal(await page.locator('.header-cta').count(),0);
  assert.equal(await page.locator('a[aria-label="Instagram da Organzza Debutantes"]').getAttribute('href'),'https://www.instagram.com/organzzadebutantes/');
  await page.locator('#cart-open').click();assert.equal(await page.locator('#checkout-open').isDisabled(),true);await page.locator('#cart-close').click();
  await page.locator('[data-add="aurora"]').click();assert.equal(await page.locator('.cart-item').count(),1);await page.locator('#cart-continue').click();
  await page.locator('[data-add="aqua"]').click();assert.equal(await page.locator('#cart-count').textContent(),'2');await page.locator('#cart-close').click();
  await page.reload();assert.equal(await page.locator('#cart-count').textContent(),'2');
  await page.locator('[data-add="aurora"]').click();assert.equal(await page.locator('.cart-item').count(),2);await page.locator('#cart-close').click();
  const admin=await context.newPage();admin.on('pageerror',e=>errors.push(e.message));await admin.goto('http://localhost:4187/admin.html');
  assert.equal(await admin.locator('#statTotal').textContent(),'7');
  await admin.locator('[data-id="aurora"] [data-action="edit"]').click();
  await admin.locator('#productName').fill('Aurora Teste');await admin.locator('#productPrice').fill('750');await admin.locator('#productPromo').fill('690');await admin.locator('#productSizes').fill('36, 38');
  await admin.locator('#productForm button[type="submit"]').click();
  await page.waitForFunction(()=>document.querySelector('[data-dress="aurora"].product-name')?.textContent==='Aurora Teste');
  await page.locator('#cart-open').click();await page.locator('[data-cart-size="aurora"]').selectOption('36');
  assert.match(await page.locator('#cart-total').textContent(),/1\.880/);
  await page.locator('#checkout-open').click();await page.locator('[name="name"]').fill('Maria Teste');await page.locator('[name="phone"]').fill('(27) 99999-9999');await page.locator('[name="notes"]').fill('Quero experimentar os dois vestidos.');
  await page.evaluate(()=>{window.open=url=>{window.__checkoutUrl=url;return null;};});
  await page.locator('#checkout-form button[type="submit"]').click();
  const checkoutUrl=new URL(await page.evaluate(()=>window.__checkoutUrl));assert.equal(checkoutUrl.searchParams.get('phone'),'5527999073556');
  const message=checkoutUrl.searchParams.get('text');assert.match(message,/Aurora Teste \(ORG-01\)/);assert.match(message,/Tamanho: 36/);assert.match(message,/Aqua \(ORG-04\)/);assert.match(message,/Maria Teste/);assert.match(message,/Quero experimentar os dois vestidos/);assert.match(message,/690/);assert.match(message,/1\.190/);
  await page.locator('#cart-open').click();await page.locator('[data-cart-remove="aqua"]').click();assert.equal(await page.locator('#cart-count').textContent(),'1');await page.locator('#checkout-open').click();
  const visit=await page.evaluate(()=>{const date=new Date();date.setDate(date.getDate()+2);while(date.getDay()===0)date.setDate(date.getDate()+1);const value=AppointmentStore.toDateValue(date);return {date:value,time:AppointmentStore.availableSlots(value)[0]};});
  await page.locator('[name="visitDate"]').fill(visit.date);await page.locator('[name="visitTime"]').selectOption(visit.time);await page.locator('#checkout-form button[type="submit"]').click();
  await page.locator('#checkout-dialog').waitFor({state:'hidden'});const pending=await page.evaluate(()=>AppointmentStore.getAppointments());assert.equal(pending.length,1);assert.equal(pending[0].status,'pending');assert.equal(pending[0].dresses[0].size,'36');
  await admin.reload();await admin.evaluate(()=>AppointmentStore.ready);await admin.locator('#agendaDate').fill(visit.date);assert.equal(await admin.locator('.agenda-slot.booked').count(),1);assert.match(await admin.locator('.agenda-slot.booked').textContent(),/Maria Teste/);
  await admin.locator('[data-appointment-action="confirm"]').click();await page.waitForFunction(()=>AppointmentStore.getAppointments()[0].status==='scheduled');
  await admin.locator('[data-id="aurora"] [data-action="decrease"]').click();await page.waitForFunction(()=>document.querySelector('#cart-count').textContent==='0');
  assert.equal(await page.locator('[data-add="aurora"]').isDisabled(),true);
  await admin.locator('[data-id="rubi"] [data-action="toggle"]').click();await page.waitForFunction(()=>!document.querySelector('[data-dress="rubi"]'));
  await admin.locator('#newProduct').click();await admin.locator('#productName').fill('Modelo Teste');await admin.locator('#productColor').fill('Azul');await admin.locator('#productSizes').fill('32, 36');
  await admin.locator('#productImages').setInputFiles('assets/809910695.webp');await admin.locator('#imagePreview img').waitFor();await admin.locator('#productForm button[type="submit"]').click();
  await page.getByRole('button',{name:'Ver fotos do vestido Modelo Teste',exact:true}).waitFor();await page.getByRole('button',{name:'Ver fotos do vestido Modelo Teste',exact:true}).click();
  assert.equal(await page.locator('#dress-price').textContent(),'Valor sob consulta');assert.equal(await page.locator('#thumbnails button').count(),1);await page.locator('#dress-size').selectOption('32');await page.locator('#dress-add').click();assert.equal(await page.locator('.cart-item').count(),1);assert.match(await page.locator('.cart-item').textContent(),/Modelo Teste/);await page.locator('#cart-close').click();
  await page.evaluate(()=>{localStorage.clear();});await page.reload();await admin.close();
  await page.setViewportSize({width:390,height:844});await page.locator('[data-add="aurora"]').click();await page.screenshot({path:'previews/sacola-mobile.png'});
  assert.equal(await page.locator('#cart-dialog').evaluate(el=>el.scrollWidth>el.clientWidth),false);
  await page.locator('#checkout-open').click();assert.equal(await page.locator('#checkout-dialog').evaluate(el=>el.scrollWidth>el.clientWidth),false);await page.screenshot({path:'previews/checkout-mobile.png'});await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!document.body.classList.contains('modal-open'));
  await page.evaluate(()=>localStorage.clear());await page.reload();
  assert.deepEqual(errors,[]);
  console.log('OK: layout em 320/390/768/1440 px, galerias, favoritos, sacola persistente, remoção, tamanhos, resumo WhatsApp, painel, preços/promoções, disponibilidade, agenda e sincronização entre abas.');
} finally {await browser.close();server.kill();await new Promise(r=>{if(server.exitCode!==null)r();else server.once('exit',r);});assert.ok(path.resolve(testDirectory).startsWith(path.join(os.tmpdir(),'organzza-site-test-')));await rm(testDirectory,{recursive:true,force:true});}
